# Generated by Django 3.2.9 on 2021-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
        migrations.AddField(
            model_name='icon',
            name='bots',
            field=models.ImageField(null=True, upload_to='bots'),
        ),
        migrations.AddField(
            model_name='icon',
            name='shrooms',
            field=models.ImageField(null=True, upload_to='shrooms'),
        ),
    ]
