# Generated by Django 3.2.9 on 2021-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_auto_20211214_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='bots',
            field=models.FileField(null=True, upload_to='bots'),
        ),
    ]
