# Generated by Django 3.2.9 on 2021-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_auto_20211214_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='bots')),
            ],
        ),
        migrations.CreateModel(
            name='shroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='shrooms')),
            ],
        ),
        migrations.DeleteModel(
            name='icon',
        ),
    ]
